import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/card";
import { fetchStore } from "../lib/coffee-store";
import { useTrackLocation } from "../hooks/use-track-location";
import { useEffect, useState } from "react";
import { StoreContext } from "../context/store-context";
import { useContext } from "react";
import { ACTION_TYPE } from "../context/store-context";

export async function getStaticProps(context) {
  const formattedData = await fetchStore("23.73,90.37", 6);
  return {
    props: { storeData: formattedData }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  const [storesNearMe, setStoresNearMe] = useState([]);
  const ctx = useContext(StoreContext);
  const { state, dispatch } = ctx;
  const { handleTrack, locationErrorMsg, isFindingLocation } =
    useTrackLocation(dispatch);

  const handleOnButtonClick = () => {
    handleTrack();
  };

  useEffect(() => {
    console.log("latLong", state.latLong);
    console.log("error", locationErrorMsg);

    async function setCoffeeStoresByLocation() {
      if (state.latLong.length > 0) {
        // code
        const stores = await fetchStore(state.latLong, 30);
        // setStoresNearMe(stores);
        dispatch({ type: ACTION_TYPE.SET_STORE, payload: stores });
        console.log({ stores });
      }
    }

    setCoffeeStoresByLocation();
  }, [state.latLong, locationErrorMsg]);

  const handleIncrementCount = () => {
    console.log("increment count");
    ctx.dispatch({
      type: ACTION_TYPE.INCREMENT_COUNT,
      payload: 2,
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>BuzzCoffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.heroImage}>
          <Image
            src={"/static/hero-image.png"}
            width={"700px"}
            height={"400px"}
          />
        </div>
        <Banner
          buttonText={isFindingLocation ? "Loading...." : "View Store Nearby"}
          handleOnClick={handleOnButtonClick}
        />

        {state.stores.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Stores near me</h2>
            <div className={styles.cardLayout}>
              {state.stores.map((each) => {
                return (
                  <Card
                    className={styles.card}
                    title={each.name}
                    imgUrl={each.imgUrl}
                    url={each.id}
                    key={each.id}
                  />
                );
              })}
            </div>
          </div>
        )}

        {props.storeData.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Dhaka stores</h2>
            <div className={styles.cardLayout}>
              {props.storeData.map((each) => {
                return (
                  <Card
                    className={styles.card}
                    title={each.name}
                    imgUrl={each.imgUrl}
                    url={each.id}
                    key={each.id}
                  />
                );
              })}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
