import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/card";

export default function Home() {
  const handleOnButtonClick = () => {
    console.log("hi button click");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>BuzzCoffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.heroImage}>
          <Image
            src={"/static/hero-image.png"}
            width={"700px"}
            height={"400px"}
          />
        </div>
        <Banner
          buttonText={"View Store Nearby"}
          handleOnClick={handleOnButtonClick}
        />
        <div className={styles.cardLayout}>
          <Card className={styles.card} />
          <Card className={styles.card} />
        </div>
      </main>
    </div>
  );
}
